"use client";
import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'
import { Inter } from 'next/font/google'
import NavigationBar from './links';
import  { useEffect } from 'react';
import { Provider } from 'react-redux';
import { photoStore } from './ServerCommunication/Communicator';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 
  useEffect(() => {
    import('bootstrap/dist/js/bootstrap.bundle.min.js');
    }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Provider store={photoStore}>
          <NavigationBar />
          {children}
          </Provider>
        </div>
        </body>
    </html>
  )
}
