"use client";
import 'bootstrap/dist/css/bootstrap.min.css'
//import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import './globals.css'
import { Inter } from 'next/font/google'
import NavigationBar from './links';
import { Provider } from 'react-redux';
import { photoStore } from './ServerCommunication/Communicator';
import Script from 'next/script';
import Link from 'next/link';
import { useEffect } from 'react';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  useEffect(()=>{
    if (typeof window !== "undefined") {
      require('bootstrap/dist/js/bootstrap.bundle.min.js');
    }
  },[]); 
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script> */}
        <div className="container">
        
          <Provider store={photoStore}>
          <NavigationBar />
          {children}
          </Provider>
        </div>
      </body>
    </html>
  )
}
