"use client";
import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'
import { Inter } from 'next/font/google'
import Script  from 'next/script';
import NavigationBar from './links';
import  { useEffect } from 'react';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    import('bootstrap/dist/js/bootstrap.bundle.min.js');
    }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <NavigationBar />
        </div>
        <div>
          {children}
        </div>  
        </body>
    </html>
  )
}
